name: User Story
description: Create a new user story with acceptance criteria and definition of done
title: "User Story: "
labels: ["user story"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template

        **As a [role],**  
        **I want [an action or feature],**  
        **So that [a reason or benefit].**

  - type: textarea
    id: role
    attributes:
      label: As a [role]
      description: Describe the user or stakeholder.
      placeholder: e.g., As a registered user
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: I want [an action or feature]
      description: Describe what the user wants to do.
      placeholder: e.g., I want to upload a profile picture
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: So that [a reason or benefit]
      description: Explain why this feature or action is valuable.
      placeholder: e.g., So that I can personalize my account
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Acceptance Criteria
        - [ ] Criteria 1: Describe the first acceptance criterion here.
        - [ ] Criteria 2: Describe the second acceptance criterion here.
        - [ ] Criteria 3: Describe additional criteria as needed.

        ### Definition of Done
        - [ ] All acceptance criteria are met.
        - [ ] Code is reviewed and approved.
        - [ ] Necessary tests are written and pass.
        - [ ] Documentation is updated, if applicable.
